name: Docker Image CI

on:
  schedule: # “End of the day”
    - cron: "0 0 * * 3"

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        CWD = pwd
        cp $CWD/LICENSE $CWD/build
        cd $CWD/build
        docker build . -t jhonesto/tor-socks
    
    - name: Push to dockerhub registry
      run: |
        echo "${{ secrets.DOCKERHUB }}" | login -u jhonesto --password-stdin 
        docker push jhonesto/tor-socks:latest
    
